#!/bin/sh

# Source local POSIX sh settings (if interactive):
if \
	(case "${-}" in (*i*) exit 0;; esac; exit 1) \
	&& test -r "${HOME}/.shrc"
then
	. "${HOME}/.shrc"
fi

# Source local sync environment:
. "${HOME}/.sync/profile"


#===========================================================================
# Localization
#---------------------------------------------------------------------------

export LANG="en_GB.UTF-8"


#===========================================================================
# Functions
#---------------------------------------------------------------------------

#---------------------------------------------------------------------------
# Internal

_SET_ADD() {
	SET_NAME="${1:?}"
	SET_VALUE="$(eval printf '%s' "\$${1:?}")"
	DELIMITER="${2:?}"
	ADDITION="${3:?}"
	TOK="$(
		if test "${DELIMITER}" == ':'; then
			printf ','
		else
			printf ':'
		fi
	)"
	ADDITION_ESCAPED="$(
		printf '%s' "${ADDITION}" \
		| sed 's/${TOK}/\\${TOK}/g'
	)"
	eval "${SET_NAME}"="$(
		printf '%s' "${SET_VALUE}" "${DELIMITER}" \
		| sed "
			s${TOK}${ADDITION_ESCAPED}${DELIMITER}${TOK}${TOK}g
			s${TOK}${DELIMITER}\$${TOK}${TOK}
		"
	)"
	eval "${SET_NAME}"="\${${SET_NAME}:+\${${SET_NAME}}${DELIMITER}}${ADDITION}"
}


#===========================================================================
# Path
#---------------------------------------------------------------------------

_SET_ADD PATH : "${XDG_DATA_HOME:-$HOME/.local/share}/bash"
_SET_ADD PATH : "${XDG_DATA_HOME:-${HOME}/.local/share}/java"
_SET_ADD PATH : "${XDG_DATA_HOME:-${HOME}/.local/share}/python"
_SET_ADD PATH : "${XDG_DATA_HOME:-${HOME}/.local/share}/ruby"
_SET_ADD PATH : "${XDG_DATA_HOME:-${HOME}/.local/share}/sh"
_SET_ADD PATH : "${HOME}/.local/bin"
_SET_ADD PATH : "${HOME}/bin"
_SET_ADD PATH : "${HOME}/go/bin"
_SET_ADD PATH : '/var/lib/flatpak/exports/bin'
_SET_ADD PATH : "${HOME}/Documents/Git/github.com/andrew-ls/gantt/bin"
_SET_ADD PATH : "${HOME}/Documents/Git/github.com/andrew-ls/termpong/bin"

test "${STEAM_LIBRARY_FOLDERS}" \
&& _SET_ADD PATH : "$(
	IFS=':'
	unset -v \
		paths
	for LIBRARY in ${STEAM_LIBRARY_FOLDERS}; do
		paths="${paths:+${paths}:}${LIBRARY}/steamapps"
	done
	printf '%s' "${paths}"
)"


#===========================================================================
# Libraries
#---------------------------------------------------------------------------

_SET_ADD GTK3_MODULES : '/usr/local/lib/libplotinus.so'


#===========================================================================
# Environment
#---------------------------------------------------------------------------

# Default terminal text editor:
export EDITOR=" \
	f() {
		SETTINGS='$(printf '%s\n' \
			'let g:gitgutter_enabled = 0' \
			'source ~/.vimrc' \
			'set nonumber norelativenumber'
		)'
		if test \
			\"\$(cat \"\${TMPDIR:-/tmp}/EDITOR-vimrc\" 2> /dev/null)\" \
				!= \"\${SETTINGS}\"
		then
			rm \"\${TMPDIR:-/tmp}/EDITOR-vimrc\" 2> /dev/null
			printf '%s\n' \"\${SETTINGS}\" \
			> \"\${TMPDIR:-/tmp}/EDITOR-vimrc\"
		fi
		if test \"$(command -v vimx)\"; then
			vimx -u \"\${TMPDIR:-/tmp}/EDITOR-vimrc\" \"\${@}\"
		elif test \"$(command -v vim)\"; then
			vim -u \"\${TMPDIR:-/tmp}/EDITOR-vimrc\" \"\${@}\"
		else
			vi \"\${@}\"
		fi
	}; f \
"

# Default `fc` editor:
export FCEDIT="${EDITOR}"

# Default pager:
export PAGER='less -FKMRS'

# Default shell:
export SHELL='/usr/bin/bash'

# Default Wine prefix:
export WINEPREFIX="${HOME}/.wine"


#===========================================================================
# Application Preferences
#---------------------------------------------------------------------------

# Enable dark GTK theme for NeovimGtk:
export NVIM_GTK_PREFER_DARK_THEME='1'

# ShellCheck default options:
#   SC1090: Can't follow non-constant source.
export SHELLCHECK_OPTS=' \
	-e SC1090 \
'

# Set default systemd pager:
export SYSTEMD_PAGER='less -FKMRS'


