#!/bin/sh

# Source local POSIX sh settings (if interactive):
if \
	(case "${-}" in (*i*) exit 0;; esac; exit 1) \
	&& test -r "${HOME}/.shrc"
then
	. "${HOME}/.shrc"
fi

# Source local sync environment:
. "${HOME}/.sync/profile"


#===========================================================================
# Localization
#---------------------------------------------------------------------------

export LANG="en_GB.UTF-8"


#===========================================================================
# Functions
#---------------------------------------------------------------------------

#---------------------------------------------------------------------------
# Internal

_SET_ADD() {
	SET_NAME="${1:?}"
	SET_VALUE="$(eval printf '%s' "\$${1:?}")"
	PREFIX="$(test "${2}" == '--prefix' && printf 'true')"
	test "${PREFIX}" && shift
	DELIMITER="${2:?}"
	ADDITION="${3:?}"
	set --

	TOK="$(
		if test "${DELIMITER}" == ':'; then
			printf ','
		else
			printf ':'
		fi
	)"
	ADDITION_ESCAPED="$(
		printf '%s' "${ADDITION}" \
		| sed 's/${TOK}/\\${TOK}/g'
	)"
	eval "${SET_NAME}"="$(
		printf '%s' "${SET_VALUE}" "${DELIMITER}" \
		| sed "
			s${TOK}${ADDITION_ESCAPED}${DELIMITER}${TOK}${TOK}g
			s${TOK}${DELIMITER}\$${TOK}${TOK}
		"
	)"
	if test "${PREFIX}"; then
		eval "${SET_NAME}"="${ADDITION}\${${SET_NAME}:+${DELIMITER}\${${SET_NAME}}}"
	else
		eval "${SET_NAME}"="\${${SET_NAME}:+\${${SET_NAME}}${DELIMITER}}${ADDITION}"
	fi
}


#===========================================================================
# Path
#---------------------------------------------------------------------------

_SET_ADD PATH --prefix : "${XDG_DATA_HOME:-${HOME}/.local/share}/sh/launch"
_SET_ADD PATH : "${XDG_DATA_HOME:-$HOME/.local/share}/bash"
_SET_ADD PATH : "${XDG_DATA_HOME:-${HOME}/.local/share}/java"
_SET_ADD PATH : "${XDG_DATA_HOME:-${HOME}/.local/share}/python"
_SET_ADD PATH : "${XDG_DATA_HOME:-${HOME}/.local/share}/ruby"
_SET_ADD PATH : "${XDG_DATA_HOME:-${HOME}/.local/share}/sh"
_SET_ADD PATH : "${HOME}/.local/bin"
_SET_ADD PATH : "${HOME}/bin"
_SET_ADD PATH : "${HOME}/go/bin"
_SET_ADD PATH : '/var/lib/flatpak/exports/bin'
_SET_ADD PATH : "${HOME}/Documents/Git/github.com/andrew-ls/gantt/bin"
_SET_ADD PATH : "${HOME}/Documents/Git/github.com/andrew-ls/termpong/bin"

test "${STEAM_LIBRARY_FOLDERS}" \
&& _SET_ADD PATH : "$(
	IFS=':'
	unset -v \
		paths
	for LIBRARY in ${STEAM_LIBRARY_FOLDERS}; do
		paths="${paths:+${paths}:}${LIBRARY}/steamapps"
	done
	printf '%s' "${paths}"
)"


#===========================================================================
# Libraries
#---------------------------------------------------------------------------

_SET_ADD GTK3_MODULES : '/usr/local/lib/libplotinus.so'


#===========================================================================
# Environment
#---------------------------------------------------------------------------

# Default terminal text editor:
export EDITOR="$(
	if test -r "${HOME}/.vimrc.EDITOR"; then
		VIMRC="${HOME}/.vimrc.EDITOR"
	else
		VIMRC="${HOME}/.vimrc"
	fi

	if test "$(command -v vimx)"; then
		printf '%s\n' "vimx -u '${VIMRC}'"
	elif test "$(command -v vim)"; then
		printf '%s\n' "vim -u '${VIMRC}'"
	else
		printf '%s\n' 'vi'
	fi
)"

# Default `fc` editor:
export FCEDIT="${EDITOR}"

# Default pager:
export PAGER='less -FKMRS'

# Default shell:
export SHELL='/usr/bin/bash'

# Default Wine prefix:
export WINEPREFIX="${HOME}/.wine"


#===========================================================================
# Application Preferences
#---------------------------------------------------------------------------

# Enable dark GTK theme for NeovimGtk:
export NVIM_GTK_PREFER_DARK_THEME='1'

# Set default systemd pager:
export SYSTEMD_PAGER='less -FKMRS'


